# Generated by Django 3.2.25 on 2025-06-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lacouturière',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('puntuacion', models.IntegerField()),
                ('fecha_visita', models.DateField()),
                ('reseñador', models.CharField(max_length=100)),
                ('precio_accesible', models.BooleanField(default=True)),
            ],
        ),
    ]
